### ISSUE TITLE
[Book] Detail view

### ISSUE THREAD

**Issue by zikosw** [ce-saig/LeafBox#104]
นับจำนวนสื่อแต่ละชนิด และแสดงผล (มีช่องให้แสดงผลแล้วแต่ยังไม่ได้นับจำนวน)

**Comment by Drnutsu** [comment]
@EnceladusIApetus  ไอซ์ทำแล้วใช่ป่าวๆ พอดีพี่เห็นว่ามันมี count แล้ว

**Comment by Drnutsu** [comment]
@EnceladusIApetus  งั้นพี่ปิดเลยนะ
