### ISSUE TITLE
Borrow - media list

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#12]
สื่อที่ถูกยืมไปแล้วต้องไม่แสดงอีก (เมื่อกดเลือกไปแล้วรายการสื่อนี้ต้องหายไปจาก list)

**Comment by EnceladusIApetus** [comment]
This issue was already solved.

**Comment by Drnutsu** [comment]
ok, please send a pull request for merge to develop kub.

**Comment by EnceladusIApetus** [comment]
I've already sent pull request on branch bug/borrow-searching-media krub.
