### ISSUE TITLE
[Book] Media - edit summary media data

### ISSUE THREAD

**Issue by EnceladusIApetus** [ce-saig/LeafBox#122]
- สามารถแก้ไขข้อมูลสรุปของแต่ละสื่อได้

**Comment by zikosw** [comment]
@EnceladusIApetus ตอนคลิกที่รายการสื่อแล้วอ่ะ modal ที่ขึ้นมามันเป็นช่องว่างน่ะ อยากให้โหลดค่าเก่าใส่ไว้ใน input ด้วย
แล้วก็ช่วยคอมเม้นโค้ด console.log ออกด้วย

**Comment by zikosw** [comment]
braille คลิกแก้ไขสื่อแล้วมันไปผิดที่อ่ะ ตอนนี้ยังแก้ไขข้อมูลเบรลล์ไม่ได้
