### ISSUE TITLE
[Book] Detail - media production status should not be edited directly

### ISSUE THREAD

**Issue by EnceladusIApetus** [ce-saig/LeafBox#144]
- each media production status should be updated or changed automatically by the system.

**Comment by zikosw** [comment]
สถานะน่าจะมี
- ไม่ได้ผลิต
- กำลังผลิต
- ผลิต

ปล. ต้องดูแชทที่คุยกับ ค.กำพล วันนั้นว่ามันมีอะไรบ้าง

**Comment by EnceladusIApetus** [comment]
close at pr #156
