### ISSUE TITLE
[Return] many bugs.

### ISSUE THREAD

**Issue by EnceladusIApetus** [ce-saig/LeafBox#145]
- [x] cannot return or delete some book.
- [x] duplicate media.
- [x] borrower name disappear when refresh the browser.
- [x] media id incorrect.
- [x] error when the user delete the media that are not returned.
- [x] nothing has changed when the user added a DVD.
- [x] productive info on the book's detail page are not updated when the production status are changed.

**Comment by zikosw** [comment]
หน้าแก้ไข้ขอมูลหนังสือ
- [x] ประเภทหนังสือ - เข้า DB แต่ไม่แสดงผล ทั้งหน้า ดู และ แก้ไข
- [x] วันลงทะเบียน - คือฟิลด์ไหนของ DB
- [x] ISBN - ทำ placeholder/ตัวอย่าง ให้ผู้ใช้รู้ว่าต้องใส่ข้อมูลแบบไหน
- [x] created_at/update_at - ระบบใส่ค่าที่ผิดๆเข้าไป
