### ISSUE TITLE
Librarian can get borrower borrow status.

### ISSUE THREAD

**Issue by Drnutsu** [ce-saig/LeafBox#25]
+ บรรณารักษ์สามารถ เห็นรายการยืม และ รายการคืน ของผู้ยืมได้
issue นี้อาจจะต้องใช้หน้าแสดงผู้ใช้ร่วมกับ [#24]  
- แสดงรายการบันทึกการยืมทั้งหมด
- แต่ละรายการต้องมีข้อมูลสถานะการยืมด้วยว่า คืนหรือยัง
- จัดการย้ายไฟล์โค้ด ไปอยู่ในที่ที่เหมาะสมด้วย ตอนนี้จาก #24 ไฟล์มันยังอยู่ไม่ค่อยจะถูกที่ (สร้างโฟลเดอร์ให้มันหน่อย)

**Comment by jigkoxsee** [comment]
It's done?

**Comment by Drnutsu** [comment]
No sorry, that's my mistake.
