### ISSUE TITLE
bug/return improve return system

### ISSUE THREAD

**Issue by EnceladusIApetus** [ce-saig/LeafBox#35]
- ~~ต้องเลือกผู้ยืมก่อนทำการเพิ่มสื่อที่จะคืน~~
- ~~แจ้งเตือนเมื่อไม่มีรหัสของสื่อที่จะทำการคืน~~
- ~~แจ้งเตือนเมื่อการทำรายการเสร็จสมบูรณ์~~
- ~~เพิ่มคอลัมน์แสดงวันที่ทำการยืมสื่อ~~

----
### ยืม
 - คอลัมน์ ไอดีชองสื่อ ใส่ตัวย่อไปข้างหน้าด้วยแบบ DVD1
 - เลขไอดีเอาเป็นแบบ ไม่ต้องมี 0 นำหน้าทุกอันเลย จะได้ไม่งง ไม่ต้องเติมแบบ 1 => 001

### คืน
 - เลขไอดีเอาเป็นแบบ ไม่ต้องมี 0 นำหน้าทุกอันเลย จะได้ไม่งง ไม่ต้องเติมแบบ 1 => 001

**Comment by jigkoxsee** [comment]
ตอนนี้มันต้องเลือก ผู้ยืมก่อนถึงจะใส่รหัสหนังสื่อได้ - ต้องมี tool tips หรือข้อความอะไรบอกหน่อยว่าให้เลือก ผู้ยืม ก่อน

**Comment by Drnutsu** [comment]
@EnceladusIApetus  Please add tool tips like Ziko said. 

##### you should create new branch to do this work.

**Comment by zikosw** [comment]
@EnceladusIApetus  ตอนคืน นี่ต้องทำยังไงอ่ะ คือกรอกรหัสแล้วกดเพิ่มก็ไม่มีอะไรขึ้นอ่ะ ถ้าดูจาก console จะเห็นว่ามัน return 500, Ajax เลยเจ๊ง
- ใส่ placeholde/tooltips วิธีการใช้ไว้หน่อย (ตัวอย่างสิ่งที่ต้องกรอก)
- ตอนกดเพิ่มถ้าไม่เจออะไรก็บอกด้วยว่าไม่เจอ

**Comment by zikosw** [comment]
@EnceladusIApetus  postAdd
รับ media-id เช่น cd1,cd01,cd001,CD1 (พวกนี้เหมือนกันหมด - เจอ 0ข้างหน้าให้ตัดออก ส่วนตรง media type ให้ upper/lower ก่อน)
- เอา media id ที่ได้ไปดูก่อนว่ามัน reserved อยู่ไหม ถ้า reserved อยู่ค่อยไปดูต่อที่ table X-borrow
- ตอน if ไม่ต้องใช้ in_array หรอก ใช้ == เอาก็ได้ ใช้วิธีทำ upper/lower case เอา

**Comment by zikosw** [comment]
@EnceladusIApetus  หน้ายืมอ่ะ คอลัมน์ ไอดีชองสื่อ ใส่ตัวย่อไปข้างหน้าด้วยแบบ DVD1
บั๊กและอื่นๆจะเขียนไว้ที่ comment แรกนะ
