### ISSUE TITLE
decorate borrow list -- now it's look like plain text.

### ISSUE THREAD

**Issue by Drnutsu** [ce-saig/LeafBox#43]
![screenshot from 2015-07-20 12 16 55](https://cloud.githubusercontent.com/assets/3327427/8770372/a3d807dc-2eda-11e5-97ec-2f0577d45b5a.png)

please decorate to beautiful table or any other UI.

**Comment by zikosw** [comment]
@Drnutsu  Why I didn't see any PR?

**Comment by zikosw** [comment]
@Drnutsu  @EnceladusIApetus  You should add some interactive that tell user when they click on media that already in a list. (May be already have this issue)
