### ISSUE TITLE
Book editor page

### ISSUE THREAD

**Issue by MokiMeki** [ce-saig/LeafBox#47]
1. Use "หมายเหตุ" instead of "โน๊ต"
1. Column Should be in this order "สถานะ วันที่ หมายเหตุ"
1. Media status,note,when didn't load their existing value
1. Change button text from "แก้ไข" to "บันทึก" (Can't revert edit?) >> add Cancel btn
1. Year should be in "พ.ศ."
1. Year drop down is 275760?
1. Default of 
"สถานะ" should be "ไม่ผลิต"
"วันที่" should be "วันนี้"
otherwise show latest record

**Comment by zikosw** [comment]
ref #48
