### ISSUE TITLE
Delete media

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#5]
ไม่ควรจะกดแล้วลบทุกอันทันที
แก้ให้กดปุ่มแล้วมีให้เลือกก่อนว่าจะลบชิ้นไหนของสื่อชนิดนั้นบ้างแล้วให้กดยืนยันอีกทีเพื่อลบ

**Comment by Drnutsu** [comment]
Fixed at branch bug/delete-all-media
