### ISSUE TITLE
[Book] Media - add

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#50]
1. Sometimes show "หน้า","ชิ้น" << This isn't a bug >> Change text describe to be more clear meaning of it
1. ~~Status didn't update~~
1. ~~Move "เพิ่ม" btn to rigth-side or somewhere more makesense (meaning)~~

**Comment by Drnutsu** [comment]
Is this issue still have some incomplete problem ?

**Comment by zikosw** [comment]
@Drnutsu  Yes, As in the 1'st comment

**Comment by Drnutsu** [comment]
fixed all :) at #67
