### ISSUE TITLE
[Book] Media - remove

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#51]
1. Delete media item should have Confirmation
1. Change text "ลบสื่อนี้" to "ลบรายการสื่อนี้ทั้งหมด" or something more clear
1. Can't delete one item at a time ( Error when click "ลบ" )

**Comment by Drnutsu** [comment]
@jigkoxsee  third checklist is work for me. I don't know, Did you tried it by yourself ? or list it from aj. comment document.

**Comment by Drnutsu** [comment]
already done  ,but waiting for check third problem on checklist.

**Comment by zikosw** [comment]
@Drnutsu  error when click on table header

**Comment by Drnutsu** [comment]
fixed at #63
