### ISSUE TITLE
Edit Datepicker to B.D.

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#55]
แก้เป็นภาษาไทยและรูปแบบภาษาไทย - วัน,เดือน,ปี พ.ศ.

**Comment by jigkoxsee** [comment]
http://www.thaicreate.com/community/how-to-localize-datepicker.html

**Comment by zikosw** [comment]
Just found solution http://jojosati.github.io/bootstrap-datepicker-thai/

**Comment by zikosw** [comment]
ref #54

**Comment by zikosw** [comment]
@Drnutsu http://jojosati.github.io/bootstrap-datepicker-thai/ ลงให้หน่อยดิ งง

**Comment by Drnutsu** [comment]
already fixed.
but still have some cleaning work left.
