### ISSUE TITLE
Borrow Book search

### ISSUE THREAD

**Issue by jigkoxsee** [ce-saig/LeafBox#6]
-รองรับการกรอกไอดีของสื่อ CD100,C100,110
-แจ้งเมื่อไม่มีผลลัพธ์การค้นหา

**Comment by EnceladusIApetus** [comment]
This issue was already solved.

**Comment by Drnutsu** [comment]
Are you already sent a pull request ?

**Comment by EnceladusIApetus** [comment]
I've already done.
