### ISSUE TITLE
[Book] Add book prod status

### ISSUE THREAD

**Issue by zikosw** [ce-saig/LeafBox#85]
- วันปฏิบัติ
- CD,TAPE - อ่าน,ทำต้นฉบับ,ทำกล่อง,ส่งตรวจ
- ผู้ปฏิบัติ
- วันเสร็จ
## Module
- [x] Add
- [x] View
- [x] Edit
- [x] Delete
- [x] ล็อกการเพิ่มสถานะ ต้องเพิ่มสถานะตามลำดับเท่านั้น อ่าน,ทำกล่อง,...
- [x] ล็อกการเพิ่มสื่อนั้นๆจนการจะใส่ข้อมูล วันเสร็จของสถานะส่งตรวจ
- [x] ห้ามให้มีการเพิ่มสถานะเดียวกันมากกว่า1รายการในสื่อ1ชนิด
- [x] Goto Prod tab after add,edit (refresh page)
- [ ] _shortcut_ Implement finish all prod (for lazy insertion) (ถาม อ. ว่าต้องทำไหม)
## Note
- สถานะการผลิตของเบรลล์ น่าจะไม่เหมือนสื่อชนิดอื่น (ไม่ต้องมีอ่าน, ดูสื่ออื่นๆด้วย)

**Comment by jigkoxsee** [comment]
Need to lock add new media function untill product status finish is fill

**Comment by EnceladusIApetus** [comment]
shortcut อ. บอกว่าไม่ต้องทำครับ

**Comment by EnceladusIApetus** [comment]
สถานะการผลิต คุณกำพลจะส่งรายละเอียดมาให้ผมพรุ่งนี้ครับ

**Comment by zikosw** [comment]
OK

**Comment by EnceladusIApetus** [comment]
อ. บอกว่า shortcut ไม่ต้องทำครับ
