### ISSUE TITLE
[borrow] Search

### ISSUE THREAD

**Issue by zikosw** [ce-saig/LeafBox#94]
- ค้นหา "ก" ไม่พบ แต่ "กฎ" พบ
- ฟิลด์ที่ค้นหาได้ควรเหมือนหน้าแรก
- ~~ควรมีตัวเลือกว่าค้นหาเฉพาะ ที่ไม่ถูกยืม หรือทั้งหมด~~

**Comment by zikosw** [comment]
@oat9002 ยังไม่เสร็จน้าาาา

**Comment by oat9002** [comment]
close at pr #152
